### ISSUE TITLE
✨ Add route to allow user to change username

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-backend#243]

**Comment by shnizzedy** [comment]
In [my response](https://matter-lab.slack.com/archives/CRALZK8K0/p1578495926000100) to [a question on Slack](https://matter-lab.slack.com/archives/CRALZK8K0/p1578410022071600?thread_ts=1578335121068900&cid=CRALZK8K0):

> We clearly need better documentation around the intended flow and the status quo. A few relevant points here:
> * The `/user` routes interact with both the `User` and `Profile` data models dynamically. Generally, calls to `/user/{id}` deal with `Profile`s and calls to `/user` without `{id}` deal with the logged in `User`. 
> * That screenshot is from the Girder interface which is, as far as I understand for our use cases, intended for development but not for general users (favoring our own interfaces). We haven't been maintaining the Girder interface except for gradually restricting what data are visible there. I suspect we'll eventually pare it all the way down to just a login/logout for the interactive Swagger documentation.
> * I think where in the interface a change-username action happens is beyond the scope of this issue, which is to either add a new API route or update an existing route to allow that action to happen through the API.

The screenshot referenced therein: 
> ![Girder GUI screnshot](https://user-images.githubusercontent.com/5974438/71989801-5115e680-3200-11ea-9cd2-fa8c98eaf4df.png)

**Comment by shnizzedy** [comment]
A point of clarification: we're [phasing out `userId` visibility](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/153), so we'll either need to restrict to the logged-in user (eg, https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/ac133722bda67b20e872851a5be62c0ce416b425/girderformindlogger/api/v1/user.py#L387) or use a profile ID or login name to identify the user being updated (eg, https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/ac133722bda67b20e872851a5be62c0ce416b425/girderformindlogger/api/v1/user.py#L164).

**Comment by shnizzedy** [comment]
Proposed solutions:

| #605 | #607 | [:memo: Report](https://drive.google.com/file/d/12swUPLeo5tXaszEcrwV1EG99qx_2lyOB/view) |
| --- | --- | --- |
| ~~`PUT /user/{id}`~~ | `PUT /user/login`<br/>`PUT /user/{id}/login` | `PUT /user/{id}`<br/>`PUT /userUpdate/{id}` |

**Comment by shnizzedy** [comment]
> @shnizzedy please confirm that this requested API endpoint is intended for ADMIN user use only, or an ordinary user will be able to change his/her username also?

― https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/607#issuecomment-574415981

> Any user should be able to change their own username, and I don't think there's any reason for an admin to be able to change another user's username. I'm not even sure if usernames are or should be findable; their main use is just for logging in. All user roles are at the applet level, but usernames (`login`) are part of the User class.
> 
> ![users in relationship to content](https://user-images.githubusercontent.com/5974438/72447757-e1fe3c00-3783-11ea-9054-45115750c639.png)

― https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/607#issuecomment-574719348

**Comment by WorldImpex** [comment]
works per @devbtech
