### ISSUE TITLE
🐛 Evening activity still appears as Due although I completed it several times.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-backend#606]
I can’t determine what is happening on ChildMindInstitute/mindlogger-app#630 without reviewing logs on the back-end side. After finishing an activity the app is sending the list of responses for each question but I can’t confirm if they are being stored or not. It seems not because when the app get all the responses in the data tab I don’t see responses for those questions except for Morning Activity. Also after finishing Evening activity still appears as Due although I completed it several times.

![Screen Shot 2020-01-13 at 11 37 39](https://user-images.githubusercontent.com/16896205/72275435-eac40600-35fb-11ea-825f-21092ad22b66.png)

As you can see here I have responses for the Morning questions but not from the Evening downloaded from the back-end

![Screen Shot 2020-01-13 at 11 38 00](https://user-images.githubusercontent.com/16896205/72275462-f7485e80-35fb-11ea-9667-c90729a5276a.png)

And here you can see that the Evening activity is still Due although I completed it several times.

@shnizzedy  What do you think? should I continue on with this issue? I spent a lot of time debugging several components of the app trying to decipher any error on the app side but I can’t find none. If I could check the back-end logs maybe I could understand what’s happening and solve the issue.

_Originally posted by @Eden2016 in https://github.com/ChildMindInstitute/mindlogger-app/issues/630#issuecomment-573764600_

**Comment by shnizzedy** [comment]
I haven't been able to replicate, and this activity is part of an applet that [will be abandoned soon](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/609#issuecomment-574826123). 

![evening data](https://user-images.githubusercontent.com/5974438/72560530-37fedc80-3875-11ea-8492-69a0941a1042.png)

![evening scheduled](https://user-images.githubusercontent.com/5974438/72560185-852e7e80-3874-11ea-8d1d-3e8dca88388d.png)

My best guess is that @Eden2016's cache of that applet had/has [invalid schedule settings](https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/39), so no matter what, [the comparisons that place the activities in groups](https://github.com/ChildMindInstitute/mindlogger-app/blob/5fd1f3c6f2116c42a747bbd6d9721ec50218e96a/app/components/ActivityList/sortActivities.js#L16-L76) land that activity in "due."

Today I caught and fixed a bug (https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/614/files#diff-2929b7721c871fc46fd6145d2f910d3fR343-R357) that was preventing some user cache updates from occurring, depending how they were triggered. This fix will be live once https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/614 is deployed.

In the meantime, @Eden2016, if you go to https://api.mindlogger.org and log in (1), then click "Web API" (2) to get to the interactive API docs while you are authenticated,

![API login](https://user-images.githubusercontent.com/5974438/72562378-45b66100-3879-11ea-8a51-64b89c7d9d72.png)

then scroll down to `GET /user/applets`, set `refreshCache` to `true`, and click "Try it out!",

![GET /user/applets](https://user-images.githubusercontent.com/5974438/72562484-8a41fc80-3879-11ea-85cd-7be88d0acae9.png)

wait ~10 minutes, then on the mobile app pull down on the applets list to refresh your local cache on your mobile app,

![refresh](https://user-images.githubusercontent.com/5974438/72562991-b1e59480-387a-11ea-8fc0-f37e3a292c34.gif)

then if you complete the "evening" activity, I expect it will move to "scheduled" for its next scheduled occurrence.

All that said, I do think this is an issue with the way the schedule is or was set on an outdated applet, so the whole issue may be moot apart from illustrating the gravity of https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/39 and https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/613.

**Comment by WorldImpex** [comment]
fixed
