### ISSUE TITLE
👮 Applet names should not be able to be duplicated

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-backend#609]
The hierarchy of documents in MindLogger, per database, is as follows:

* A **database** can have any number of **applets**.
* An **applet** parameterizes exactly one **protocol** for a specific set of users. Roles, permissions, schedules, and customization all happen at the **applet** level.
* A **protocol** is composed of one or more **activities**.
* An **activity** is composed of any number of **screens** and/or **activities**.
* A **screen** is composed of one or more UI components.

![Document hierarchy](https://user-images.githubusercontent.com/5974438/74377334-b6399a80-4db1-11ea-9465-5b089407e2fe.png)

See [:books: README#data-structure](https://github.com/ChildMindInstitute/mindlogger-app-backend#data-structure) for more detailed definitions of the data structure of MindLogger.

**Applets**, **Protocols**, **Activities**, and **Screens** all have names, and different applets with a name in common has caused much confusion for developers. See https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/30 for the discussion leading to this issue. Currently, a new applet default to the name of its protocol.

To resolve this issue, 
1. [ ] design a strategy for
    - [ ] checking for any existing applets with the same name as an applet being created or renamed
    - [ ] if an applet with that name already exists, renaming the new applet without giving the creator of the new applet details of the existing same-name applet
2. [ ] implement that strategy

**Comment by shnizzedy** [comment]
![Mike Milham](https://user-images.githubusercontent.com/5974438/72465725-ae340e00-37a5-11ea-8466-ad7ab1b8dcdc.png) suggested we clear out all of the old applets at some point. Once this issue is resolved could be a good time to do that.

**Comment by WebTalentTop** [comment]
Hi, @shnizzedy. May I ask a question?
I tried to open swagger (localhost:8080/api/v1) and I get nothing.
Can you help me how to test the API on local end?

**Comment by shnizzedy** [comment]
> Hi, @shnizzedy. May I ask a question?
> I tried to open swagger (localhost:8080/api/v1) and I get nothing.
> Can you help me how to test the API on local end?

@WebTalentTop ― I opened a new issue (#643) to discuss.

**Comment by shnizzedy** [comment]
Hint: the following semantic keys are preferred to the base-level `name` key, so the strategy employed will need to consider how to handle precedence across all these keys.

https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/71bff5ddcab3597b92968e18a2e62e07ec609e02/girderformindlogger/constants.py#L104

**Comment by shnizzedy** [comment]
To clarify, the current strategy for displaying a name for an applet is to display the applet's protocol's preferred name, falling back on the applet's `name` field only if none of the `PREFERRED_NAMES` keys exist in the protocol

**Comment by shnizzedy** [comment]
> See [Schema Standardization](https://github.com/ReproNim/reproschema#schema-standardization) for more about the motivations and implementation of protocols in this project.

― https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/625#discussion_r380763970

**Comment by WorldImpex** [comment]
![File (6).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/10b305e8-8fb2-4a64-9a7e-35f474ea7755)

Works as expected
