### ISSUE TITLE
🔐 Deprecated route exposes sensitive data.

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/mindlogger-app-backend#617]
We definitely don't want to expose the whole unfiltered User model, which includes the [userId](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/153), the [cryptographic salt](https://en.wikipedia.org/wiki/Salt_(cryptography)), and the user's cached applets.

[… A]n existing deprecated route needs to be updated to prevent the exposure of the same sensitive data: https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/76abb94e8214449e1bf19e6fd3718e603631b15f/girderformindlogger/api/v1/user.py#L739

_Originally posted by @shnizzedy in https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/616_

**Comment by WorldImpex** [comment]
@devbtech Could you confirm this is working as expected?

**Comment by shnizzedy** [comment]
@WorldImpex the [PR I put in for this issue](https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/618) is still open, and with other changes that happened since the PR was opened [it failed the CI tests on the most recent merge](https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/618/commits/9e036bb699660dac8d755ad019fb7ac2cad7c374).
