### ISSUE TITLE
UpdateCache error

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/mindlogger-app-backend#699]
Updating large objects of the applet leads to problems both with notifications and blocking of some queries due to long access to the database.

need to reconsider the approach to updating applets that ends with an error in the thread.
```
raise DocumentTooLarge("%r command document too large" % (operation,))
pymongo.errors.DocumentTooLarge: 'update' command document too large
```
because of this, the front end sends events without ids. this leads to the re-inserting and resent of the notification to users.

**Comment by shnizzedy** [comment]
excerpts from [Slack](https://matter-lab.slack.com/archives/CDWA2JM7H/p1586373406255500):

> The issue is related to our database design.
> documents in users collection might exceed 16MB because of cached field.
> I think we have to redesign users collection, specially cached field.
> my idea is to use dbRef to resolve this issue.
> and I think we can make one more collection (caches) in the database. 

> 16MB is a lot of BSON data for a single document! dbRef's a great idea, although I think they're slower than manual references.
>  > Unless you have a compelling reason to use DBRefs, use manual references instead.
>
> ― https://docs.mongodb.com/manual/reference/database-references/
> If the individual applets are cached, would the performance be fast enough to just cache a list of applet _ids in the user cache and load those caches individually?

> The idea of sharing a collection can fix this problem, but also make the code more readable.
> will be better to use ODM (like an ORM but for Document based databases)
> For example Ming. it extends pymongo providing:
> * Declarative Models
> * Schema Validation
> * One-To-Many, Many-To-One and Many-To-Many Relations
>
> and much more. it would be more readable
> but in our case maybe will be better to extend base model with this Db Refs
> the decrease in performance with this approach will not be noticeable.
> but we will get away from the problem with large updating of objects

> [:+1:]

> I think manual ref is better than dbRef.
> because
> 1. it's faster than dbRef.
> 2. all of our backend code is written using manual ref
> 3. dbRef have some weak points that manual ref don't have.

**Comment by shnizzedy** [comment]
More from [Slack](https://matter-lab.slack.com/archives/CDWA2JM7H/p1586450889265700):

> Yesterday, I checked caching logic in detail.
> and found some problems/solutions in current database design for caching.

> At the moment we are having cached parameter in users collection and applet collection.
> so, each applets in folder collection exceeds 2MB in size.
> and size of user document is about 2M * (number of applets for user).
> so, backend could return exception if one user have more than 7-8 applets.
> This increases data usage dramatically and also decrease speed of all reading queries on these collections.

> I wonder if we really need caching for user collection.
> and also, I think it'll be better to remove cached parameter in applet data and make separate document to save cached data.

> @Ihor Sabram I totally agree. since current structure can lead to a complete failure of the system with an increase in the number of users and applets for them.
> it is good that MongoDB allows us to do large nesting of documents. But at least everything should be structured at the database level.
> By building the correct structure, we can validate the fields before they are added to the database.
> I think the cache is redundant data that we could collect from existing documents (tables). And somewhere, it’s easy to split the existing cache documents into separate documents (tables) and build model relationship at the model level.

> Yeah, I think caching needs a real overhaul. Everything, or nearly everything, to do with caching has been slapdash in service of seat-of-our-pants demos. I don't have the capacity to spend time designing a good strategy, but one is definitely needed for scale. As far as strategizing, I did start the epic https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/613 to try to pull together all the known outstanding issues regarding caching, to try to have a big-picture in mind when caching inevitably needs to be dealt with. Based on the fact that Wil and Arno each reached out to me individually to ask me to help you (after I chimed in on the [previous thread](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/699#issuecomment-611757910) and before this thread opened) makes me think the day has come where this issue needs to be handled rather than slapping on another bandage.

**Comment by WorldImpex** [comment]
with new data structure this error will not be present
